### PR TITLE
add alert block

### PR DESCRIPTION
**Pull request by Hitansh-Shah**
I have added a new block `AlertBlock` in streamfield of `ContentPage`. 
image

### CODE REVIEW

**Review by vossisboss — APPROVED** [review]
The feature works well and looks good in mobile and tablet displays. I think it's good to go. Any thoughts on the code details @allcaps?

**Comment by Hitansh-Shah** [comment]
One more thing, currently I have used a simple `TextBlock` for the body of the AlertBlock. Should I use something else instead like `RichTextBlock`?

**Comment by tomdyson** [comment]
Yes, while Alertbox content shouldn't need formatting, it may include links.

**Comment by Hitansh-Shah** [comment]
> Yes, while Alertbox content shouldn't need formatting, it may include links.

Yess. I guess I will include a richtextblock with specified features (like links)

**Comment by Hitansh-Shah** [comment]
I have changed alert body from `TextBlock` to `RichTextBlock` with `features=["bold", "italic", "link"]`.

**Pull request merged**
