### PR TITLE
dark and light theme functionality

### PR DESCRIPTION
**Pull request by nicklee**
Dark / light mode support for https://github.com/wagtail/guide/issues/180

### CODE REVIEW

**Comment by nicklee** [comment]
Screenshot 2022-10-25 at 12 12 52
Screenshot 2022-10-25 at 12 12 55

**Review by allcaps — CHANGES_REQUESTED** [review]
I took this for a test drive. It looks awesome!

Some feedback: navigating in dark mode gives a flash on page load. This both annoying and not accessible.

**Comment by lb-** [comment]
> Some feedback: navigating in dark mode gives a flash on page load. This both annoying and not accessible.

@nicklee you will need to put the core theme logic into the body element to solve the flashing issues. It can still be a single bundled script file but needs to be blocking rendering unfortunately to get this behaviour to be smooth. From the research I did. 

See how we solved this with Sphinx theme. https://github.com/wagtail/sphinx_wagtail_theme/pull/217

**Comment by nicklee** [comment]
Thanks @allcaps and @lb- , I've just implemented this as per @lb- suggestion, would be great if you could take a look when you have a mo

**Review by allcaps — APPROVED** [review]
@nicklee Thank you so much for this great contribution. And your patience. 👏

**Comment by lb-** [comment]
Thanks @nicklee - sorry I didn't get to review but glad this is now in.

**Pull request merged**
