### PR TITLE
fix menu button size

### LINKED ISSUE #211: Search & menu toggle (burger) button are different sizes
Not a huge problem but it would be nice if the two buttons next to each other (especially on mobile breakpoint) would be the same size.

* Search button is 42x42px
* Burger button is 40x30px

I do not think the icons need to be the same size, but rather the button target area should be the same.
Additionally, the focus outline transition is slightly longer on the search button for some reason (see recording).

## Screen reader

| Search | Burger |
|---|----|
|Screen Shot 2022-10-26 at 7 30 37 pm| Screen Shot 2022-10-26 at 7 30 49 pm|

## Recording

https://user-images.githubusercontent.com/1396140/197993212-b065b511-d017-4b1d-ac20-746d185cc94b.mp4

### PR DESCRIPTION
**Pull request by VictoriaAjala**
Fixes #211

**New button designs.**
Screenshot from 2022-10-31 14-35-11
Screenshot from 2022-10-31 14-37-57

### CODE REVIEW

**Review by allcaps — CHANGES_REQUESTED** [review]

**Comment by allcaps** [comment]
@VictoriaAjala can I finish the work on this one?

**Comment by VictoriaAjala** [comment]
@allcaps I'd like to finish this up but I'm not sure where to add the fix, Can you possibly help me with an Idea?

**Comment by allcaps** [comment]
@VictoriaAjala, 

I'm sorry.  I can't help you without trying myself. So, figuring this out is doing the work. Maybe proper frontend devs could help you without touching code, I can't.

For non-frontend devs (like me) this is always a bit of a puzzle. What I did:
- Use the browser developer tools to select and inspect the relevant elements (`.burger`, `.header__burger` and `.header____search-toggle`) to see what CSS selectors apply and what  properties/values they have. 
- The size and positioning properties are important (`width`, `height`, `top`, `inset`)
- If not familiar with these, look them up to get thorough understanding of how the work.
- Fiddle in the developer tools CSS panel to inspect the effects.
- Make the burger width/height properties the same a the search toggle.
- Update `inset` to place the hamburger bars in the center.
- Fiddle a bit with the values until everything looks correct.
- Check open and close menus
- Check all viewport breakpoints

Final result: 
- I made both elements 42x40 px (not exactly square, but it looks correct, the contents is horizontal and vertical centered).
- I downshifted all contents of the hamburger with 5px.

Exact changes: https://github.com/wagtail/guide/pull/265

I hope this helps you understand the work. Feel free to update your PR as an exercise. I'm happy to merge your contribution.

**Comment by VictoriaAjala** [comment]
> @VictoriaAjala,
> 
> I'm sorry. I can't help you without trying myself. So, figuring this out is doing the work. Maybe proper frontend devs could help you without touching code, I can't.
> 
> For non-frontend devs (like me) this is always a bit of a puzzle. What I did:
> 
>     * Use the browser developer tools to select and inspect the relevant elements (`.burger`, `.header__burger` and `.header____search-toggle`) to see what CSS selectors apply and what  properties/values they have.
> 
>     * The size and positioning properties are important (`width`, `height`, `top`, `inset`)
> 
>     * If not familiar with these, look them up to get thorough understanding of how the work.
> 
>     * Fiddle in the developer tools CSS panel to inspect the effects.
> 
>     * Make the burger width/height properties the same a the search toggle.
> 
>     * Update `inset` to place the hamburger bars in the center.
> 
>     * Fiddle a bit with the values until everything looks correct.
> 
>     * Check open and close menus
> 
>     * Check all viewport breakpoints
> 
> 
> Final result:
> 
>     * I made both elements 42x40 px (not exactly square, but it looks correct, the contents is horizontal and vertical centered).
> 
>     * I downshifted all contents of the hamburger with 5px.
> 
> 
> Exact changes: #265
> 
> I hope this helps you understand the work. Feel free to update your PR as an exercise. I'm happy to merge your contribution.

@allcaps Thanks , this really helps!

**Comment by thibaudcolas** [comment]
Fixed in #265

**Pull request closed without merging**
